export const MARKER_SKILLS = [
  { id: "attack", label: "Attack" },
  { id: "hitpoints", label: "Hitpoints" },
  { id: "mining", label: "Mining" },
  { id: "strength", label: "Strength" },
  { id: "agility", label: "Agility" },
  { id: "smithing", label: "Smithing" },
  { id: "defence", label: "Defence" },
  { id: "herblore", label: "Herblore" },
  { id: "fishing", label: "Fishing" },
  { id: "ranged", label: "Ranged" },
  { id: "thieving", label: "Thieving" },
  { id: "cooking", label: "Cooking" },
  { id: "prayer", label: "Prayer" },
  { id: "crafting", label: "Crafting" },
  { id: "firemaking", label: "Firemaking" },
  { id: "magic", label: "Magic" },
  { id: "fletching", label: "Fletching" },
  { id: "woodcutting", label: "Woodcutting" },
  { id: "runecraft", label: "Runecraft" },
  { id: "slayer", label: "Slayer" },
  { id: "farming", label: "Farming" },
  { id: "construction", label: "Construction" },
  { id: "hunter", label: "Hunter" },
  { id: "sailing", label: "Sailing" },
];

export const NOTES_BOXES = [
  { id: "attack", label: "Attack" },
  { id: "strength", label: "Strength" },
  { id: "defence", label: "Defence" },
  { id: "ranged", label: "Ranged" },
  { id: "magic", label: "Magic" },
  { id: "prayer", label: "Prayer" },
  { id: "hitpoints", label: "Hitpoints" },
  { id: "farming", label: "Farming" },
  { id: "fishing", label: "Fishing" },
  { id: "hunter", label: "Hunter" },
  { id: "mining", label: "Mining" },
  { id: "woodcutting", label: "Woodcutting" },
  { id: "cooking", label: "Cooking" },
  { id: "crafting", label: "Crafting" },
  { id: "fletching", label: "Fletching" },
  { id: "herblore", label: "Herblore" },
  { id: "runecraft", label: "Runecraft" },
  { id: "smithing", label: "Smithing" },
  { id: "agility", label: "Agility" },
  { id: "construction", label: "Construction" },
  { id: "firemaking", label: "Firemaking" },
  { id: "slayer", label: "Slayer" },
  { id: "thieving", label: "Thieving" },
  { id: "sailing", label: "Sailing" },
];